name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Remove the invalid setup-dotnet step

    - name: Restore dependencies
      run: dotnet restore fowlrunner.sln

    - name: Build
      run: dotnet build fowlrunner.sln --no-restore --configuration Release
