name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x' # or your project's preferred version

    - name: Restore dependencies
      run: dotnet restore fowlrunner.sln

    - name: Build
      run: dotnet build fowlrunner.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test fowlrunner.sln --no-build --verbosity normal
