name: .NET Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install .NET Framework 4.7.1 Developer Pack
      run: choco install netfx-4.7.1-devpack -y

    - name: Restore dependencies
      run: dotnet restore fowlrunner.sln

    - name: Build
      run: dotnet build fowlrunner.sln --no-restore --configuration Release
